version: 1
agents:
  - agentId: issue-validator
    slots: 1
    leaseDuration: PT30M
  - agentId: issue-info-requester
    slots: 1
    leaseDuration: PT30M
  - agentId: issue-title-validator
    slots: 1
    leaseDuration: PT30M
  - agentId: issue-body-validator
    slots: 1
    leaseDuration: PT30M
  - agentId: issue-validation-evaluator
    slots: 1
    leaseDuration: PT30M
  - agentId: demo-orchestrator
    slots: 1
    leaseDuration: PT15M
